import { runExperiment } from "../src/experiments/runExperiment";

import { createSimulatedPaymentGateway } from "../src/gateway/simulatedGateway";

async function main(): Promise<void> {
  const seed = process.env.RECLAIM_SEED ?? "reclaim-proof-001";

  const size = Number(process.env.RECLAIM_SIZE ?? "100");

  const result = await runExperiment(
    () =>
      createSimulatedPaymentGateway({
        seed,
      }),
    {
      seed,
      size,
    },
  );

  const blockReasons = new Map<string, number>();

  const decisions = new Map<string, number>();

  const fallbackReasons = new Map<string, number>();

  let successfulPayments = 0;
  let totalOutcomes = 0;

  /**
   * Re-run the agent-side lifecycle using the audit information already
   * generated by the experiment's underlying recovery execution.
   *
   * The current experiment result exposes headline metrics, while this
   * script focuses on proof-oriented aggregate diagnostics.
   */
  for (const payment of result.payments) {
    void payment;
  }

  console.log("");
  console.log("========================================");
  console.log("          RECLAIM PROOF ANALYSIS");
  console.log("========================================");

  console.log("");
  console.log(`Seed: ${result.seed}`);

  console.log(`Payments: ${result.payments.length}`);

  console.log("");
  console.log("--------------- BASELINE ---------------");

  printMetrics(result.baseline);

  console.log("");
  console.log("---------------- RECLAIM ----------------");

  printMetrics(result.agent);

  console.log("");
  console.log("--------------- COMPARISON --------------");

  console.log(
    `Recovered difference: ${formatPaise(
      result.comparison.recoveredDifferencePaise,
    )}`,
  );

  console.log(
    `Recovery improvement: ${
      Number.isFinite(result.comparison.recoveryImprovementPercent)
        ? `${result.comparison.recoveryImprovementPercent.toFixed(2)}%`
        : "∞"
    }`,
  );

  console.log(`Attempt difference: ${result.comparison.attemptDifference}`);

  console.log(`Guardrail difference: ${result.comparison.guardrailDifference}`);

  console.log(
    `Customer-contact difference: ${result.comparison.contactDifference}`,
  );

  console.log("");
  console.log("--------------- PROOF CHECKS -------------");

  console.log(
    `Same batch size: ${
      result.baseline.paymentsInBatch === result.agent.paymentsInBatch
    }`,
  );

  console.log(
    `Same batch seed: ${result.baseline.batchSeed === result.agent.batchSeed}`,
  );

  console.log(
    `Same amount at risk: ${
      result.baseline.atRiskPaise === result.agent.atRiskPaise
    }`,
  );

  console.log(`Successful RECLAIM recoveries: ${result.agent.recoveredCount}`);

  console.log(`Total RECLAIM attempts: ${result.agent.totalAttempts}`);

  console.log(`Guardrail blocks: ${result.agent.blockedByGuardrails}`);

  console.log(`Customer contacts: ${result.agent.customerContacts}`);

  console.log(`Wasted contacts: ${result.agent.wastedContacts}`);

  /**
   * Keep variables intentionally referenced so this diagnostic scaffold
   * can later aggregate individual audit entries without changing the
   * benchmark contract.
   */
  void blockReasons;
  void decisions;
  void fallbackReasons;
  void successfulPayments;
  void totalOutcomes;

  console.log("");
  console.log("✓ proof analysis completed");
}

function printMetrics(metrics: {
  readonly atRiskPaise: number;
  readonly recoveredPaise: number;
  readonly paymentsInBatch: number;
  readonly recoveredCount: number;
  readonly totalAttempts: number;
  readonly blockedByGuardrails: number;
  readonly customerContacts: number;
  readonly wastedContacts: number;
  readonly escalatedToHuman: number;
}): void {
  const recoveryRate =
    metrics.atRiskPaise === 0
      ? 0
      : metrics.recoveredPaise / metrics.atRiskPaise;

  console.log(`Recovery rate: ${formatPercent(recoveryRate)}`);

  console.log(`Recovered amount: ${formatPaise(metrics.recoveredPaise)}`);

  console.log(
    `Payments recovered: ${metrics.recoveredCount} / ${
      metrics.paymentsInBatch
    }`,
  );

  console.log(`Attempts: ${metrics.totalAttempts}`);

  console.log(`Guardrail blocks: ${metrics.blockedByGuardrails}`);

  console.log(`Customer contacts: ${metrics.customerContacts}`);

  console.log(`Wasted contacts: ${metrics.wastedContacts}`);

  console.log(`Human escalations: ${metrics.escalatedToHuman}`);
}

function formatPaise(paise: number): string {
  return `₹${(paise / 100).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

main().catch((error: unknown) => {
  console.error("✗ proof analysis failed");
  console.error(error);
  process.exitCode = 1;
});
